export const FETCH_PLAYERS = "FETCH_PLAYERS";
export const FETCH_SINGLEPLAYER_BOARDS = "FETCH_SINGLEPLAYER_BOARDS";

export const FETCH_TEAMS = "FETCH_TEAMS";
export const FETCH_MULTIPLAYER_BOARDS = "FETCH_MULTIPLAYER_BOARDS";
